Casoca/tabelas/urls.py
#Core Django imports
from django.conf.urls import url

from .views import (
    TransportadorasList, TransportadorasCreate, TransportadorasUpdate, TransportadorasDelete
)

urlpatterns = [
    # Transportadoras
    url(r'^listatransportadoras/$',TransportadorasList.as_view(),name='lista-transportadoras'),
    url(r'^novatransportadora/$',TransportadorasCreate.as_view(),name='nova-transportadora'),
    url(r'^editatransportadora/(?P<pk>\d+)/$',TransportadorasUpdate.as_view(),name='edita-transportadora'),
    url(r'^excluitransportadora/(?P<pk>\d+)/$', TransportadorasDelete.as_view(),name='exclui-transportadora'),

]

Casoca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Casoca.principal import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login', views.loginview, name='login'),
    url(r'^logout', views.logoutview, name='logout'),
    url(r'^admin/', admin.site.urls),

    url(r'^apifrete/', include('Casoca.apifrete.urls')),
    url(r'^magento/', include('Casoca.magento.urls', namespace="magento")),
    url(r'^planilhas/', include('Casoca.excel.urls', namespace="planilhas")),
    url(r'^tabelas/',include('Casoca.tabelas.urls', namespace="tabelas")),
]

Casoca/tabelas/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES

from Casoca.principal.choices import SIM_NAO

class Transportadoras(models.Model):

    cnpj = models.CharField('CNPJ', max_length=18, blank=True, null=True)
    identificador = models.CharField('Identificador', max_length=5)
    loja = models.ForeignKey('magento.marketplace_userdata',verbose_name='Loja', blank=True, null=True)
    nome_fantasia = models.CharField('Transportadora', max_length=60)
    razao_social = models.CharField('Razão Social', max_length=200, blank=True, null=True)
    codigo_contrato = models.CharField('Código do Contrato de Logística', max_length=60, blank=True, null=True)
    inscricao_estadual = models.CharField('Inscrição Estadual', max_length=25, blank=True, null=True)
    inscricao_minicipal = models.CharField('Inscrição Municipal', max_length=25, blank=True, null=True)
    endereco = models.CharField('Endereço', max_length=60)
    numero = models.PositiveSmallIntegerField('Número')
    complemento = models.CharField('Complemento',max_length=10, blank=True, null=True)
    bairro = models.CharField('Bairro',max_length=20)
    cep = models.CharField('CEP', max_length=9)
    cidade = models.CharField('Cidade',max_length=50)
    uf = models.CharField('Unidade da Federação', max_length=2, choices=STATE_CHOICES, default='MG')
    telefone = models.CharField('Telefone de Contato', max_length=15, blank=True, null=True)
    contatos = models.TextField("Informações de Contatos", blank=True, null=True)
    habilitado = models.CharField('Habilitado', max_length=1, choices=SIM_NAO, default='S', blank=True, null=True)
    criado = models.DateTimeField("Criado em", auto_now_add=True)
    modificado = models.DateTimeField("Modificado em", auto_now=True)

    class Meta:
        verbose_name = 'Transportadora'
        verbose_name_plural = 'Transportadoras'
        ordering = ['nome_fantasia', 'cidade']
        unique_together=[('loja','identificador'),]

    def __str__(self):
        return self.nome_fantasia + ' - ' + self.cidade + '-' + self.uf


class Fretes(models.Model):

    loja = models.ForeignKey('magento.marketplace_userdata',verbose_name='Loja')
    transportadora = models.ForeignKey(Transportadoras, verbose_name="Transportadora")
    peso_inicial = models.DecimalField('Peso Inicial', decimal_places=2, max_digits=10)
    peso_final = models.DecimalField('Peso Final', decimal_places=2, max_digits=10)
    cep_inicial = models.DecimalField('CEP Inicial', decimal_places=2, max_digits=10)
    cep_final = models.DecimalField('CEP Final', decimal_places=2, max_digits=10)
    tempo_entrega = models.PositiveSmallIntegerField('Tempo de Entrega')
    volume_maximo = models.DecimalField('Volume Máximo', decimal_places=2, max_digits=10)
    peso_cubado = models.DecimalField('Peso Cubado', decimal_places=2, max_digits=10)
    dt_inicio = models.DateField("Data Início de Vigência")
    dt_final = models.DateField("Data Final de Vigência")
    custo_acessorial = models.DecimalField('Custo Acessorial', decimal_places=3, max_digits=5)
    valor_minimo = models.DecimalField('Valor Mínimo', decimal_places=2, max_digits=10)
    fator_multiplicacao = models.DecimalField('Valor Fator de Multiplicação', decimal_places=2, max_digits=10)
    custos_adicionais = models.DecimalField('Custos Adicionais', decimal_places=2, max_digits=10)
    criado = models.DateTimeField("Criado em", auto_now_add=True)
    modificado = models.DateTimeField("Modificado em", auto_now=True)

    class Meta:
        verbose_name = 'Fretes'
        verbose_name_plural = 'Fretes'
        ordering = ['transportadora__nome_fantasia', 'peso_inicial']
        unique_together=[('loja','transportadora','dt_inicio'),]

    def __str__(self):
        return self.transportadora.nome_fantasia + ': ' + self.peso_inicial + '-' + self.peso_final

Casoca/tabelas/forms.py
from django import forms

from localflavor.br.forms import BRCNPJField, BRPhoneNumberField, BRZipCodeField

from .models import Transportadoras, Fretes
from Casoca.magento.models import marketplace_userdata

class TransportadorasForm(forms.ModelForm):

    cnpj = BRCNPJField(label='CNPJ',
                       widget=forms.TextInput(
                           attrs={
                               'class': 'form-control cnpj',
                               'placeholder': '99.999.999/9999-99',
                               'title': 'CNPJ no formato 99.999.999/9999-99',
                           }
                       ),
                       min_length=15,
                       required=True)


    identificador = forms.CharField(label='Identificador da transportadora',
                                   widget=forms.TextInput(attrs={
                                       'class': 'form-control',
                                       'placeholder': 'XXXXX',
                                   }),
                                   help_text='Identificador da transportadora utilizado para associar aos produtos.',
                                   required=True,
                                   max_length=5
                                   )

    nome_fantasia = forms.CharField(label='Nome Fantasia',
                                   widget=forms.TextInput(attrs={
                                       'class': 'form-control',
                                       'placeholder': 'Nome Fantasia',
                                   }),
                                   required=True,
                                   max_length=60
                                   )

    razao_social = forms.CharField(label='Razão Social',
                                  widget=forms.TextInput(attrs={
                                      'class': 'form-control',
                                      'placeholder': 'Razão Social',
                                  }),
                                  required=True,
                                  max_length=100
                                  )

    endereco = forms.CharField(label='Endereço',
                               widget=forms.TextInput(attrs={
                                   'placeholder': 'Rua, avenida, praça ....',
                                   'class': 'form-control',
                               }),
                               required=True,
                               max_length=60
                               )

    numero = forms.IntegerField(label='Número',
                                     widget=forms.NumberInput(attrs={
                                         'class': 'form-control',
                                     }),
                                     required=True,
                                     )

    bairro = forms.CharField(label='Bairro',
                             widget=forms.TextInput(attrs={
                                 'class': 'form-control',
                             }),
                             required=True,
                             max_length=50
                             )

    cidade = forms.CharField(label='Cidade',
                             widget=forms.TextInput(attrs={
                                 'class': 'form-control',
                             }),
                             required=True,
                             initial='Belo Horizonte',
                             max_length=50
                             )

    telefone = BRPhoneNumberField(widget=forms.TextInput(attrs={
        'class': 'form-control phone',
        "placeholder": "(99)9999-9999",
        "title": "Telefone de contato no formato (99)99999-9999"}),
        required=False,
    )

    cep = BRZipCodeField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        "placeholder": "99999-999",
        "title": "CEP no formato 99999-999"}),
        max_length=9,
        required=True,
    )


    class Meta:
        model = Transportadoras
        fields = ['loja','cnpj', 'identificador', 'nome_fantasia', 'razao_social', 'codigo_contrato', 'inscricao_estadual', 'inscricao_minicipal',
                  'telefone', 'endereco', 'numero', 'complemento', 'bairro', 'cep', 'cidade', 'uf', 'contatos', 'habilitado']

        widgets = {

            "loja": forms.Select(
                attrs={
                    'class': 'form-control',
                },
            ),

            "codigo_contrato": forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Código do contrato junto à transportadora'
                },
            ),

            "inscricao_estadual": forms.TextInput(
                attrs={
                    'class': 'form-control',
                },
            ),

            "inscricao_minicipal": forms.TextInput(
                attrs={
                    'class': 'form-control',
                },
            ),

            'complemento': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Informações adicionais ao endereço',
                }
            ),
            'uf': forms.Select(
                attrs={
                    'class': 'form-control',
                }
            ),
            'contatos': forms.Textarea(
                attrs={
                    'class': 'form-control',
                }
            ),
            "habilitado": forms.Select(
                attrs={
                    'class': 'form-control',
                },
            ),
        }

        help_texts = {
            'cnpj': (
                'Cadastro Nacional da Pessoa Jurídica'
            ),
            'cep': (
                'Insira somente os números do cep.'
            ),
            'endereco': (
                'Rua, avenida, viela...'
            ),
            'numEndereco': (
                'Número do endereço.'
            ),
            'complemento': (
                'Complemento para este endereço.'
            ),
            'bairro': (
                'Bairro ou distrito.'
            ),
            'cidade': (
                'Cidade deste endereço.'
            ),
        }

Casoca/tabelas/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from .forms import TransportadorasForm
from .models import Transportadoras, Fretes
#
# #############
# # Transportadoras
#
class TransportadorasList(LoginRequiredMixin, ListView):
    model = Transportadoras
    template_name = 'tabelas/lista_transportadoras.html'
    def get_queryset(self):

        try:
            empresas = Transportadoras.objects.order_by('nome_fantasia').all()
        except Transportadoras.DoesNotExist:
            empresas = Transportadoras()

        return empresas


class TransportadorasCreate(LoginRequiredMixin, CreateView):
    model = Transportadoras
    template_name = 'tabelas/form_padrao.html'
    form_class =  TransportadorasForm
    success_url = reverse_lazy('tabelas:lista-empresas')

    def get_context_data(self, **kwargs):
        data = super(TransportadorasCreate, self).get_context_data(**kwargs)
        data['tabela'] = 'Transportadoras'
        data['list_url'] = 'tabelas:lista-transportadoras'
        data['operacao'] = 'Incluir'
        return data


class TransportadorasUpdate(LoginRequiredMixin, UpdateView):
    model = Transportadoras
    template_name = 'tabelas/form_padrao.html'
    form_class =  TransportadorasForm
    success_url = reverse_lazy('tabelas:lista-transportadoras')

    def get_context_data(self, **kwargs):
        data = super(TransportadorasUpdate, self).get_context_data(**kwargs)
        data['tabela'] = 'Transportadoras'
        data['list_url'] = 'tabelas:lista-transportadoras'
        data['operacao'] = 'Salvar'
        return data


class TransportadorasDelete(LoginRequiredMixin, DeleteView):
    model = Transportadoras
    template_name = 'tabelas/confirma_exclusao.html'
    success_url = reverse_lazy('tabelas:lista-transportadoras')

    def get_context_data(self, **kwargs):
        data = super(TransportadorasDelete, self).get_context_data(**kwargs)
        data['tabela'] = 'Transportadoras'
        data['list_url'] = 'tabelas:lista-transportadoras'
        return data

Casoca/tabelas/templates/tabelas/confirma_exclusao.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}
    <h3>
        {{title}}
        <small>{{description}}</small>
    </h3>
{#    <ol class="breadcrumb">#}
{#        <li>#}
{#            <a href="{% url 'dashboard' %}">#}
{#                <i class="fa fa-dashboard"></i>#}
{#                Dashboard#}
{#            </a>#}
{#        </li>#}
{#        {% if tabela == "Tipo de Receita" %}#}
{#            <li>#}
{#                <a href="{% url 'tables:list-tipo-receita' %}">#}
{#                    <i class="fa fa-table"></i>#}
{#                    {{ tabela }}#}
{#                </a>#}
{#            </li>#}
{#        {% elif tabela == "Tipo de Despesa" %}#}
{#            <li>#}
{#                <a href="{% url 'tables:list-tipo-despesa' %}">#}
{#                    <i class="fa fa-table"></i>#}
{#                    {{ tabela }}#}
{#                </a>#}
{#            </li>#}
{#        {% elif tabela == "Forma de Recebimento" %}#}
{#            <li>#}
{#                <a href="{% url 'tables:list-forma-recebimento' %}">#}
{#                    <i class="fa fa-table"></i>#}
{#                    {{ tabela }}#}
{#                </a>#}
{#            </li>#}
{#        {%  endif %}#}
{#        <li class="active">#}
{#            Excluir#}
{#        </li>#}
{#    </ol>#}
{% endblock %}
{% block conteudo %}

<div class="row">
    <div class="col-md-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="">
                    {%  if produtoid %}
                        <h1><a href="{% url list_url pk=produtoid %}" >{{ tabela }} </a></h1>
                    {%  else %}
                        <h1><a href="{% url list_url  %}" >{{ tabela }} </a></h1>
                    {% endif %}
				</h1>
            </div>


            <form role="form" method="post">{% csrf_token %}
                <div class="panel-body">
					<div class="alert alert-danger">
                        <i class="fa fa-ban"></i>
						<b>Alerta!</b>
						Você tem certeza que deseja excluir	o {{ tabela|lower }}: {{ object }} ?
                    </div>
                </div>
                <div class="panel-footer">
                    <button type="submit" class="btn btn-danger">
                        Excluir
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

Casoca/tabelas/templates/tabelas/form_padrao.html
{% extends "base.html" %}
{% load static %}

{% block conteudo %}

    <div class="col-md-12">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- general form elements -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1><a href="{% url list_url  %}" >{{ tabela }} </a></h1>
                </div>
                <!-- /.box-header -->

                <div class="panel-body">
                    {{ form.as_p }}
                </div>
            </div>

            <div class="panel-footer">
                <button type="submit" class="btn btn-danger">{{ operacao }}</button>
                <br/><br/>
            </div>
        </form>
    </div>

{% endblock %}

Casoca/tabelas/templates/tabelas/lista_transportadoras.html
{% extends 'base.html' %}
{% block conteudo %}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading"><h1>Transportadoras</h1></div>

            <div class="panel-body">
                <p></p>
            </div>
            <!-- Table -->
            <table class="table">
                <tr>
                    <td><b> <a href="{% url 'tabelas:nova-transportadora' %}"><span class="glyphicon glyphicon-plus-sign"
                                   aria-hidden="true"></span></a></b>
                    </td>
                    <td align="center"><b>Identificador</b></td>

                    <td><b>Nome Fantasia</b></td>
                    <td><b>Telefone</b></td>
                    <td><b>Cidade</b></td>
                    <td><b>CNPJ</b></td>
                    <td  align="center"><b>Habilitado</b></td>
                </tr>
                {% for transportadora in transportadoras_list %}
                    <tr>
                        <td><a href="{% url 'tabelas:edita-transportadora' transportadora.pk %}"> <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a></td>
                        <td align="center"> {{ transportadora.identificador }} </td>
                        <td> {{ transportadora.nome_fantasia }} </td>
                        <td> {{ transportadora.telefone }} </td>
                        <td> {{ transportadora.cidade }}/{{ transportadora.uf }}  </td>
                        <td> {{ transportadora.cnpj }} </td>
                        <td align="center"> {{ transportadora.habilitado }} </td>
                    </tr>
                {% endfor %}
            </table>
        </div>


{% endblock %}