Casoca/excel/urls.py
from django.conf.urls import url


from Casoca.excel import views

# app_name = 'excel'

urlpatterns = [
    url(r'^$', views.model_form_upload, name='upload_file'),
]

Casoca/magento/urls.py
#Core Django imports
from django.conf.urls import url

from .views import (
    LojasList,
)

urlpatterns = [
    # Lojas
    url(r'^lojas/$',LojasList.as_view(),name='lista-lojas'),
]

Casoca/tabelas/urls.py
#Core Django imports
from django.conf.urls import url

from .views import (
    TransportadorasList, TransportadorasCreate, TransportadorasUpdate, TransportadorasDelete
)

urlpatterns = [
    # Transportadoras
    url(r'^listatransportadoras/$',TransportadorasList.as_view(),name='lista-transportadoras'),
    url(r'^novatransportadora/$',TransportadorasCreate.as_view(),name='nova-transportadora'),
    url(r'^editatransportadora/(?P<pk>\d+)/$',TransportadorasUpdate.as_view(),name='edita-transportadora'),
    url(r'^excluitransportadora/(?P<pk>\d+)/$', TransportadorasDelete.as_view(),name='exclui-transportadora'),

]

Casoca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Casoca.principal import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login', views.loginview, name='login'),
    url(r'^logout', views.logoutview, name='logout'),
    url(r'^admin/', admin.site.urls),

    url(r'^apifrete/', include('Casoca.apifrete.urls')),
    url(r'^magento/', include('Casoca.magento.urls', namespace="magento")),
    url(r'^planilhas/', include('Casoca.excel.urls', namespace="planilhas")),
    url(r'^tabelas/',include('Casoca.tabelas.urls', namespace="tabelas")),
]

Casoca/principal/models.py
from django.db import models

# Create your models here.

Casoca/principal/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, 'home.html')


def loginview(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'login.html', {'mensagem': 'Usuário/senha inválidos'})
    else:
        return render(request, 'login.html')

@login_required
def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

Casoca/principal/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no">
    {% load static %}
    <title>Casoca</title>
    <link rel="icon" href="{% static 'casoca.ico'%}" type="image/x-icon"/>

    {% include 'config/bootstrap_defaults.html' %}
    {% include 'config/css.html' %}
    {% include 'config/js.html' %}

</head>

<body>
{% load static %}
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
                    data-toggle="collapse" data-target="#mynav">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'logo.png' %}" width="100" class="img-responsive center-block"></a>
        </div>
        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse" id="mynav">

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            Usuário: {{ request.user }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#" onclick="document.getElementById('logout').submit()">Logout</a></li>
                            <form id="logout" method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <input type="hidden">
                            </form>
                            <li><a href="#">Trocar Senha</a></li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            Fretes<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'planilhas:upload_file' %}">Carga de Tabelas de Frete</a></li>
                            <li><a href="#">Simular Frete</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            Tabelas<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'tabelas:lista-transportadoras' %}">Transportadoras</a></li>
                            <li><a href="{% url 'magento:lista-lojas' %}">Lojas</a></li>
                        </ul>
                    </li>
                </ul>

            </div>

        {% else %}

            <div class="collapse navbar-collapse" id="mynav">
                <ul class="nav navbar-nav navbar-right">
                    <a class="navbar-brand" href="{% url 'login' %}">Login</a>
                </ul>
            </div>

        {% endif %}

    </div>
</nav>

<div class="container">
    <br/>
    {% block conteudo %}

    {% endblock %}

    <div class="well well-sm col-md-12">

        <div class="col-md-6" align="left">

            <h4>Casoca Marketplace</h4>
            <h6>Rua:Cosmos, 44 sl 300 - Santa Lúcia<br/>
                Belo Horizonte-MG CEP: 30.360-650<br/>
                Tel.: (31) 3317-1807
            </h6>
        </div>
        <div class="col-md-6" align="right">
            <h6>Casoca<br/>
                wwww.casoca.com.br<br/>
                © 2017. (Direitos Reservados)<br/><br/>
                Criado por Criasol</h6>
        </div>
    </div>

</div>

</body>
</html>

Casoca/principal/templates/base_admin.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no">
    {% load static %}
    <title>Casoca</title>
    <link rel="icon" href="{% static 'casoca.ico'%}" type="image/x-icon"/>
    {% include 'config/bootstrap_defaults.html' %}
    {% include 'config/css.html' %}
    {% include 'config/js.html' %}

</head>

<body>
{% load static %}
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
                    data-toggle="collapse" data-target="#mynav">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'logo.png' %}" width="100" class="img-responsive center-block"></a>
        </div>
        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse" id="mynav">

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            Usuário: {{ request.user }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#" onclick="document.getElementById('logout').submit()">Logout</a></li>
                            <form id="logout" method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <input type="hidden">
                            </form>
                            <li><a href="#">Trocar Senha</a></li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            Produtos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Categorias</a></li>
                            <li><a href="#">Produtos</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            Cadastros<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Empresas</a></li>
                            <li><a href="#">Usuários Pretendentes</a></li>
                            <li><a href="#">Planos</a></li>
                        </ul>
                    </li>
                </ul>

            </div>

        {% else %}

            <div class="collapse navbar-collapse" id="mynav">
                <ul class="nav navbar-nav navbar-right">
                    <a class="navbar-brand" href="{% url 'login' %}">Login</a>
                </ul>
            </div>

        {% endif %}

    </div>
</nav>

<div class="container">
    <br/>
    {% block conteudo %}

    {% endblock %}

</div>

</body>
</html>

Casoca/principal/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block conteudo %}

    <div class="col-md-12">
        <br/><br/>
        <img src="{% static 'logo.png' %}" class="img-responsive center-block" width="400"><br/><br/>
        <h3 align="center">O Casoca tomou para si a missão de deixar a sua casa ainda mais decorada de boas lembranças!<br/>            ​
            Casoca, por uma casa viva</h3><br/>

        {% if not user.is_authenticated %}
            <div align="center">
                <a href="{% url 'login' %}" class="btn btn-danger">Login</a>
            </div>
            <br/>
        {% endif %}

    </div>

{% endblock %}

Casoca/principal/templates/login.html
{% extends 'base_admin.html' %}

{% block conteudo %}
    {% include 'config/section.html' %}
    {% load static %}

  <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

    <section>

        <h1><p style="text-align:center;">Login</p></h1>

        {%  if mensagem %}
            {{ mensagem }}
            <br><br>
        {% endif %}
        <form method="post" action="" align="center">
            {% csrf_token %}

            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}

            Usuário:<br>
            <input type="text" name="username"><br>
            Senha:<br>
            <input type="password" name="password"><br /> <br>
        <div align="center">
            <input class="btn btn-danger" type="submit" value="Login ">
        </div>
        </form>

    </section>



{% endblock %}